### ISSUE TITLE
[FE] 헤더 기능 작업

### ISSUE THREAD

**Issue by gunoc** [masters2023-2nd-project-traveler/todo-max#37]
## 진행할 작업

헤더에 필요한 기능을 작업합니다

## TODO

- [x] 기록이 많아졌을 때 스크롤
- [x] 나타나고 닫힐때 애니메이션
- [x] 기록 전체 삭제 클릭시 모달창
- [x] 모달창의 삭제 클릭시 모든 사용자 활동 내역 삭제
