### ISSUE TITLE
[FE] 카드 추가 기능

### ISSUE THREAD

**Issue by lolWK** [masters2023-2nd-project-traveler/todo-max#47]
## 진행할 작업

카드 추가 기능을 작업합니다

## TODO

- [x] 등록 버튼 클릭 시 카드 등록
- [x] 취소 버튼 클릭 시 카드 박스 사라짐
- [x] 작성자 디바이스 표시
- [x] 카드 글자 수 제한, 박스 크기 조절 기능
